---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
          - name: docker-compose
        pip_package: python3-pip
        pip_executable: pip3
    - role: geerlingguy.docker
      vars:
        docker_compose_version: "1.26.0"
        docker_edition: "ce"
        docker_version: "5:19.03.0~3-0~ubuntu-bionic"
        docker_package: "docker-{{ docker_edition }}={{ docker_version }}"
        docker_users:
          - ubuntu
    - role: asabaini.redash
